package com.bb.kanjuzi.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bb.kanjuzi.bean.SearchHistory;
import com.bb.kanjuzi.bean.DetailPageBean;

import com.bb.kanjuzi.greendao.SearchHistoryDao;
import com.bb.kanjuzi.greendao.DetailPageBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig searchHistoryDaoConfig;
    private final DaoConfig detailPageBeanDaoConfig;

    private final SearchHistoryDao searchHistoryDao;
    private final DetailPageBeanDao detailPageBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        searchHistoryDaoConfig = daoConfigMap.get(SearchHistoryDao.class).clone();
        searchHistoryDaoConfig.initIdentityScope(type);

        detailPageBeanDaoConfig = daoConfigMap.get(DetailPageBeanDao.class).clone();
        detailPageBeanDaoConfig.initIdentityScope(type);

        searchHistoryDao = new SearchHistoryDao(searchHistoryDaoConfig, this);
        detailPageBeanDao = new DetailPageBeanDao(detailPageBeanDaoConfig, this);

        registerDao(SearchHistory.class, searchHistoryDao);
        registerDao(DetailPageBean.class, detailPageBeanDao);
    }
    
    public void clear() {
        searchHistoryDaoConfig.clearIdentityScope();
        detailPageBeanDaoConfig.clearIdentityScope();
    }

    public SearchHistoryDao getSearchHistoryDao() {
        return searchHistoryDao;
    }

    public DetailPageBeanDao getDetailPageBeanDao() {
        return detailPageBeanDao;
    }

}
